export const INPUTS = [
    { id: "clear", className: "all-clear", stringName: "AC" },
    { id: "divide", className: "operand", stringName: "/" },
    { id: "multiply", className: "operand", stringName: "*" },
    { id: "seven", className: "number", stringName: "7" },
    { id: "eight", className: "number", stringName: "8" },
    { id: "nine", className: "number", stringName: "9" },
    { id: "subtract", className: "operand", stringName: "-" },
    { id: "four", className: "number", stringName: "4" },
    { id: "five", className: "number", stringName: "5" },
    { id: "six", className: "number", stringName: "6" },
    { id: "add", className: "operand", stringName: "+" },
    { id: "one", className: "number", stringName: "1" },
    { id: "two", className: "number", stringName: "2" },
    { id: "three", className: "number", stringName: "3" },
    { id: "zero", className: "zero", stringName: "0" },
    { id: "decimal", className: "decimal", stringName: "." },
    { id: "equals", className: "equals", stringName: "=" },
]